const express = require('express');
const router = express.Router();
const auth = require("../middleware/auth");

const {
  createPurchaseOrder,
  getPurchaseOrders,
  getPurchaseOrderById,
  updatePurchaseOrder,
  deletePurchaseOrder,
  autoGenerateDraftPOs
} = require('../controller/purchaseOrderController');

router.post('/create', auth, createPurchaseOrder);
router.post('/auto-generate', auth, autoGenerateDraftPOs);
router.get('/', auth, getPurchaseOrders);
router.get('/:id', auth, getPurchaseOrderById);
router.put('/:id', auth, updatePurchaseOrder);
router.delete('/:id', auth, deletePurchaseOrder);

module.exports = router;
